# Travis CI integration -- https://travis-ci.org/troglobit/libuev
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Some of the autotests may use sudo, so use non-dockerized build atm.
# http://stackoverflow.com/questions/26299552/travis-sudo-is-disabled
sudo: true

#  - make test
script:
  - ./autogen.sh
  - ./configure --disable-silent-rules
  - make -j5 clean all
