# Travis CI integration
sudo: false
language: c
compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "OAx9MdLgm+ZpCo/h65praDhKl35RgHEQRFR1qa5fLFrVxqFIusXFl4/A+xSpY+EYcmN0Vcsn5Z79dy3DqK6Njbt14s56NH1mvuDw7SxkFDijwZkJTmgjgCiDM+Hn3Vwjk9WYX0PNifX8Mcm0Zp9sci/koW523ltJdWC7ULvFzK8="

addons:
  coverity_scan:
    project:
      name: "troglobit/pimd"
      description: "pimd | The Original PIM-SM Daemon"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./configure"
    build_command:   "make"
    branch_pattern: dev

script: ./configure && make
